### ISSUE TITLE
Errors building without setting various cmake options

### ISSUE THREAD

**Issue by srobinson-kx** [KxSystems/ffi#11]
I had some troubles building this library, and with help from Simon managed to get it built by adding the below to CMakeLists.txt. This should probably be included by default when I clone the repo.  

set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99 -D_GNU_SOURCE")

**Comment by mshimizu-kx** [comment]
- `std=c99` was added.
- Also fundamental problem was that OS conditional variable was not working which should have added GNU_SOURCE automatically.
