### ISSUE TITLE
Is it possible to call a function like execve?

### ISSUE THREAD

**Issue by nugend** [KxSystems/ffi#3]
I'm having a pickle of a time trying to call execve. I can't for the life of me figure out the right way to construct and pass the argv and envp arguments to the function so that they are arrays of pointers.

Is this possible? How are you supposed to build the array of character pointers?

**Comment by sv** [comment]
Do you have a sample code and what is the outcome you get?

**Comment by nugend** [comment]
Not exactly. I've mostly just been trying to figure out how to construct an array of pointers given the existing ffi interface.

**Comment by nugend** [comment]
So I managed to get it working by adding a function to ffi.c

```
void *ptr_id(void *x){return x;}
```

And then using the following code (calls execv, but easy enough to change to execve):

```
.utl.require "ffi"
ptr_id:{.ffi.bind[`ptr_id;"R";"r"](x;::)}
args:.ffi.cstr each ("echo";"hello")
argv:(.ffi.cstr "/bin/echo";ptr_id'[args],.ffi.nil)
.ffi.cf[("I";`execv)] argv
```

This produces "hello" as expected and the call that strace spits out looks right:
```execve("/bin/echo", ["echo", "hello"], [/* 64 vars */]) = 0```

The `.utl.require "ffi"` part is just some of my library loading code and `.ffi.cstr` is a helper I defined to append a null character to the end of the strings.

So, yeah, I guess it's almost possible? Is there a better function already defined for getting the address of the underlying storage for a vector K object? I didn't see one looking at the code, but C isn't my strong suit, so maybe I didn't understand. This one has to do all that extra work that the call ffi function does. I guess I could write something more direct, but it'd probably replicate most of what getvalue is doing, I think?

**Comment by sv** [comment]
There is .ffi.deref function to work with arrays and structs. Would it work
for you?
.ffi.deref[pointer;"types of elements char array";index]
So something like .ffi.deref[raw;1#"r";0]

**Comment by nugend** [comment]
Could you spell it out for me? I don't think that there's a way of getting the raw pointer that I'd need to pass to that in the first place, right?

**Comment by mshimizu-kx** [comment]
No, there is no way of getting a raw pointer. Looks like deref function was in development. It will be deleted from code as garbage.
