### ISSUE TITLE
Accessing the K Object length

### ISSUE THREAD

**Issue by pindash** [KxSystems/ffi#6]
extern "C" void g(void* ptr)
{
  printf("%s: (%p)\n", __PRETTY_FUNCTION__, ptr);
  K k = static_cast<K>(ptr);
  printf("k = %p\n", k);
  printf("%p->t = %d\n", k, k->t);
  printf("%p->n = %lld\n", k, k->n);
 printf("---\n");

q)g[enlist ([]til 10)]
void g(void*): (0x7f7929901bd0)
k = 0x7f7929901bd0
0x7f7929901bd0->t = 98
0x7f7929901bd0->n = 140158365392032
---

For some reason n is coming as some nonsensical number. The type t is correct. I would expect n to be 10 or 1 if it is the number of columns. 

Is there a way of passing the raw k object using ffi?

**Comment by mshimizu-kx** [comment]
No, FFI supports only simple atom or list. If you want to handle raw K object, please use C API.

The code you intended might be below and it worked for me. `g2` is the function using C API.
```CXX
#include <stdio.h>
#include "k.h"

extern "C" K g(void* ptr){ 
  printf("loc: (%p)\n", ptr);
  K k = static_cast<K>(ptr);
  printf("k = %p\n", k);
  printf("%p->t = %d\n", k, k->t);
  printf("%p->n = %lld\n", k, k->n);
  printf("---\n");
  return static_cast<K>(nullptr);
}

extern "C" K g2(K object){ 
  printf("loc: (%p)\n", object);
  printf("k = %p\n", object);
  printf("%p->t = %d\n", object, object->t);
  printf("%p->n = %lld\n", object, object->n);
  K dict=object->k;
  K keys=kK(dict)[0];
  K values=kK(dict)[1];
  printf("header: %s\n-\n", kS(keys)[0]);
  for(size_t i=0; i != kK(values)[0]->n; ++i){
    printf("value[%d]: %d\n", i, kJ(kK(values)[0])[i]);
  }
  printf("---\n");
  return static_cast<K>(nullptr);
}
```

Execution in q:
```q
q)g:`some 2: (`g; 1)
q)g2:`some 2: (`g2; 1)
q)g enlist ([] a:til 10)
loc: (0x7f688e852600)
k = 0x7f688e852600
0x7f688e852600->t = 0
0x7f688e852600->n = 1
---
q)g2 ([] a:til 10)
loc: (0x7f688e801110)
k = 0x7f688e801110
0x7f688e801110->t = 98
0x7f688e801110->n = 140087044411872
header: a
-
value[0]: 0
value[1]: 1
value[2]: 2
value[3]: 3
value[4]: 4
value[5]: 5
value[6]: 6
value[7]: 7
value[8]: 8
value[9]: 9
---
```
